### ISSUE TITLE
Scale Card Footer

### ISSUE THREAD

**Issue by niteshkumar2000** [FreakyOS/freakyos.github.io#4]
Even though the existing cards are scaled properly across the device, but still when the footer text length changes (increase or decrease) it affects the card size :/

**Comment by niteshkumar2000** [comment]
https://freakyos.github.io/#/downloads

@aakashhemadri my work around was to locally sort card's footer text and render which made them looks less ugly but still this is not a solution. Need help with this.

**Comment by aakashhemadri** [comment]
It's not an issue
It's just a simple class change, will do :)
